/*
Copyright 2020 AppsCode Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "go.bytebuilders.dev/resource-model/apis/cloud/v1alpha1"
	scheme "go.bytebuilders.dev/resource-model/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KubernetesVersionsGetter has a method to return a KubernetesVersionInterface.
// A group's client should implement this interface.
type KubernetesVersionsGetter interface {
	KubernetesVersions() KubernetesVersionInterface
}

// KubernetesVersionInterface has methods to work with KubernetesVersion resources.
type KubernetesVersionInterface interface {
	Create(ctx context.Context, kubernetesVersion *v1alpha1.KubernetesVersion, opts v1.CreateOptions) (*v1alpha1.KubernetesVersion, error)
	Update(ctx context.Context, kubernetesVersion *v1alpha1.KubernetesVersion, opts v1.UpdateOptions) (*v1alpha1.KubernetesVersion, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.KubernetesVersion, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.KubernetesVersionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KubernetesVersion, err error)
	KubernetesVersionExpansion
}

// kubernetesVersions implements KubernetesVersionInterface
type kubernetesVersions struct {
	client rest.Interface
}

// newKubernetesVersions returns a KubernetesVersions
func newKubernetesVersions(c *CloudV1alpha1Client) *kubernetesVersions {
	return &kubernetesVersions{
		client: c.RESTClient(),
	}
}

// Get takes name of the kubernetesVersion, and returns the corresponding kubernetesVersion object, and an error if there is any.
func (c *kubernetesVersions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KubernetesVersion, err error) {
	result = &v1alpha1.KubernetesVersion{}
	err = c.client.Get().
		Resource("kubernetesversions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KubernetesVersions that match those selectors.
func (c *kubernetesVersions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KubernetesVersionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.KubernetesVersionList{}
	err = c.client.Get().
		Resource("kubernetesversions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kubernetesVersions.
func (c *kubernetesVersions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("kubernetesversions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kubernetesVersion and creates it.  Returns the server's representation of the kubernetesVersion, and an error, if there is any.
func (c *kubernetesVersions) Create(ctx context.Context, kubernetesVersion *v1alpha1.KubernetesVersion, opts v1.CreateOptions) (result *v1alpha1.KubernetesVersion, err error) {
	result = &v1alpha1.KubernetesVersion{}
	err = c.client.Post().
		Resource("kubernetesversions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kubernetesVersion).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kubernetesVersion and updates it. Returns the server's representation of the kubernetesVersion, and an error, if there is any.
func (c *kubernetesVersions) Update(ctx context.Context, kubernetesVersion *v1alpha1.KubernetesVersion, opts v1.UpdateOptions) (result *v1alpha1.KubernetesVersion, err error) {
	result = &v1alpha1.KubernetesVersion{}
	err = c.client.Put().
		Resource("kubernetesversions").
		Name(kubernetesVersion.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kubernetesVersion).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kubernetesVersion and deletes it. Returns an error if one occurs.
func (c *kubernetesVersions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("kubernetesversions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kubernetesVersions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("kubernetesversions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kubernetesVersion.
func (c *kubernetesVersions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KubernetesVersion, err error) {
	result = &v1alpha1.KubernetesVersion{}
	err = c.client.Patch(pt).
		Resource("kubernetesversions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
