/*
Copyright The Pharmer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	cloudv1 "pharmer.dev/cloud/apis/cloud/v1"
	versioned "pharmer.dev/cloud/client/clientset/versioned"
	internalinterfaces "pharmer.dev/cloud/client/informers/externalversions/internalinterfaces"
	v1 "pharmer.dev/cloud/client/listers/cloud/v1"
)

// MachineTypeInformer provides access to a shared informer and lister for
// MachineTypes.
type MachineTypeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.MachineTypeLister
}

type machineTypeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewMachineTypeInformer constructs a new informer for MachineType type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMachineTypeInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMachineTypeInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredMachineTypeInformer constructs a new informer for MachineType type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMachineTypeInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1().MachineTypes().List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1().MachineTypes().Watch(options)
			},
		},
		&cloudv1.MachineType{},
		resyncPeriod,
		indexers,
	)
}

func (f *machineTypeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMachineTypeInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *machineTypeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cloudv1.MachineType{}, f.defaultInformer)
}

func (f *machineTypeInformer) Lister() v1.MachineTypeLister {
	return v1.NewMachineTypeLister(f.Informer().GetIndexer())
}
