apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: pharmer
  name: cloudproviders.cloud.pharmer.io
spec:
  group: cloud.pharmer.io
  names:
    kind: CloudProvider
    listKind: CloudProviderList
    plural: cloudproviders
    singular: cloudprovider
  scope: ""
  validation:
    openAPIV3Schema:
      description: CloudProvider is the Schema for the cloudproviders API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CloudProviderSpec defines the desired state of CloudProvider
          properties:
            credentialFormat:
              description: CredentialFormat is the Schema for the credentialformats
                API
              properties:
                apiVersion:
                  description: 'APIVersion defines the versioned schema of this representation
                    of an object. Servers should convert recognized schemas to the
                    latest internal value, and may reject unrecognized values. More
                    info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
                  type: string
                kind:
                  description: 'Kind is a string value representing the REST resource
                    this object represents. Servers may infer this from the endpoint
                    the client submits requests to. Cannot be updated. In CamelCase.
                    More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                  type: string
                metadata:
                  type: object
                spec:
                  description: CredentialFormatSpec defines the desired state of CredentialFormat
                  properties:
                    displayFormat:
                      type: string
                    fields:
                      items:
                        properties:
                          envconfig:
                            type: string
                          form:
                            type: string
                          input:
                            type: string
                          json:
                            type: string
                          label:
                            type: string
                        type: object
                      type: array
                    provider:
                      type: string
                  required:
                  - displayFormat
                  - fields
                  - provider
                  type: object
              type: object
            kubernetesVersions:
              items:
                description: KubernetesVersion is the Schema for the kubernetesversions
                  API
                properties:
                  apiVersion:
                    description: 'APIVersion defines the versioned schema of this
                      representation of an object. Servers should convert recognized
                      schemas to the latest internal value, and may reject unrecognized
                      values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
                    type: string
                  kind:
                    description: 'Kind is a string value representing the REST resource
                      this object represents. Servers may infer this from the endpoint
                      the client submits requests to. Cannot be updated. In CamelCase.
                      More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                    type: string
                  metadata:
                    type: object
                  spec:
                    description: KubernetesVersionSpec defines the desired state of
                      KubernetesVersion
                    properties:
                      envs:
                        additionalProperties:
                          type: boolean
                        type: object
                      gitVersion:
                        type: string
                      major:
                        type: string
                      minor:
                        type: string
                    required:
                    - gitVersion
                    type: object
                type: object
              type: array
            machineTypes:
              items:
                properties:
                  apiVersion:
                    description: 'APIVersion defines the versioned schema of this
                      representation of an object. Servers should convert recognized
                      schemas to the latest internal value, and may reject unrecognized
                      values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
                    type: string
                  kind:
                    description: 'Kind is a string value representing the REST resource
                      this object represents. Servers may infer this from the endpoint
                      the client submits requests to. Cannot be updated. In CamelCase.
                      More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                    type: string
                  metadata:
                    type: object
                  spec:
                    description: MachineTypeSpec defines the desired state of MachineType
                    properties:
                      category:
                        type: string
                      cpu:
                        type: string
                      deprecated:
                        type: boolean
                      description:
                        type: string
                      disk:
                        type: string
                      ram:
                        type: string
                      regions:
                        items:
                          type: string
                        type: array
                      sku:
                        type: string
                      zones:
                        items:
                          type: string
                        type: array
                    required:
                    - cpu
                    - ram
                    - sku
                    type: object
                type: object
              type: array
            regions:
              items:
                description: Region defines the desired state of Region
                properties:
                  location:
                    type: string
                  region:
                    type: string
                  zones:
                    items:
                      type: string
                    type: array
                required:
                - region
                type: object
              type: array
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
