apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: pharmer
  name: credentialformats.cloud.pharmer.io
spec:
  group: cloud.pharmer.io
  names:
    kind: CredentialFormat
    listKind: CredentialFormatList
    plural: credentialformats
    singular: credentialformat
  scope: ""
  validation:
    openAPIV3Schema:
      description: CredentialFormat is the Schema for the credentialformats API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CredentialFormatSpec defines the desired state of CredentialFormat
          properties:
            displayFormat:
              type: string
            fields:
              items:
                properties:
                  envconfig:
                    type: string
                  form:
                    type: string
                  input:
                    type: string
                  json:
                    type: string
                  label:
                    type: string
                type: object
              type: array
            provider:
              type: string
          required:
          - displayFormat
          - fields
          - provider
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
