apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: pharmer
  name: kubernetesversions.cloud.pharmer.io
spec:
  group: cloud.pharmer.io
  names:
    kind: KubernetesVersion
    listKind: KubernetesVersionList
    plural: kubernetesversions
    singular: kubernetesversion
  scope: ""
  validation:
    openAPIV3Schema:
      description: KubernetesVersion is the Schema for the kubernetesversions API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: KubernetesVersionSpec defines the desired state of KubernetesVersion
          properties:
            envs:
              additionalProperties:
                type: boolean
              type: object
            gitVersion:
              type: string
            major:
              type: string
            minor:
              type: string
          required:
          - gitVersion
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
