/*
Copyright 2020 AppsCode Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "go.bytebuilders.dev/resource-model/apis/cloud/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCredentialFormats implements CredentialFormatInterface
type FakeCredentialFormats struct {
	Fake *FakeCloudV1alpha1
}

var credentialformatsResource = schema.GroupVersionResource{Group: "cloud.bytebuilders.dev", Version: "v1alpha1", Resource: "credentialformats"}

var credentialformatsKind = schema.GroupVersionKind{Group: "cloud.bytebuilders.dev", Version: "v1alpha1", Kind: "CredentialFormat"}

// Get takes name of the credentialFormat, and returns the corresponding credentialFormat object, and an error if there is any.
func (c *FakeCredentialFormats) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CredentialFormat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(credentialformatsResource, name), &v1alpha1.CredentialFormat{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CredentialFormat), err
}

// List takes label and field selectors, and returns the list of CredentialFormats that match those selectors.
func (c *FakeCredentialFormats) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CredentialFormatList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(credentialformatsResource, credentialformatsKind, opts), &v1alpha1.CredentialFormatList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CredentialFormatList{ListMeta: obj.(*v1alpha1.CredentialFormatList).ListMeta}
	for _, item := range obj.(*v1alpha1.CredentialFormatList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested credentialFormats.
func (c *FakeCredentialFormats) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(credentialformatsResource, opts))
}

// Create takes the representation of a credentialFormat and creates it.  Returns the server's representation of the credentialFormat, and an error, if there is any.
func (c *FakeCredentialFormats) Create(ctx context.Context, credentialFormat *v1alpha1.CredentialFormat, opts v1.CreateOptions) (result *v1alpha1.CredentialFormat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(credentialformatsResource, credentialFormat), &v1alpha1.CredentialFormat{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CredentialFormat), err
}

// Update takes the representation of a credentialFormat and updates it. Returns the server's representation of the credentialFormat, and an error, if there is any.
func (c *FakeCredentialFormats) Update(ctx context.Context, credentialFormat *v1alpha1.CredentialFormat, opts v1.UpdateOptions) (result *v1alpha1.CredentialFormat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(credentialformatsResource, credentialFormat), &v1alpha1.CredentialFormat{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CredentialFormat), err
}

// Delete takes name of the credentialFormat and deletes it. Returns an error if one occurs.
func (c *FakeCredentialFormats) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(credentialformatsResource, name), &v1alpha1.CredentialFormat{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCredentialFormats) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(credentialformatsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CredentialFormatList{})
	return err
}

// Patch applies the patch and returns the patched credentialFormat.
func (c *FakeCredentialFormats) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CredentialFormat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(credentialformatsResource, name, pt, data, subresources...), &v1alpha1.CredentialFormat{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CredentialFormat), err
}
