apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: pharmer
  name: credentials.cloud.pharmer.io
spec:
  group: cloud.pharmer.io
  names:
    categories:
    - pharmer
    - appscode
    kind: Credential
    listKind: CredentialList
    plural: credentials
    singular: credential
  preserveUnknownFields: false
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CredentialSpec defines the desired state of Credential
          properties:
            data:
              additionalProperties:
                type: string
              type: object
            provider:
              type: string
          required:
          - data
          - provider
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
